import { Link } from "@material-ui/core";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.scss";
import MusicByArtist from "./components/music-by-artist";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/">
        <MusicByArtist />
      </Link>
    </div>
  );
};

export default Home;
